import re

"""
Cases in requisite string:
    () and () or x
    () or x
    () and () or x
    n,n,n,n or n or x
    x and () or
    n or n, x
    None
    n or x
    Consent of instructor
    n
    n. Not open for students with credit for n or n
    class standing
    Graduate/professional standing
    Graduate standing or special student
    
    
    
    regex subject string = (AFAERO|AFRICAN|AFROAMER|AAE|BSE|LSC|AGROECOL|AGRONOMY|AMERIND|ANATOMY|ANAT\&PHY|ANESTHES|ANTHRO|ABT|ART|ARTED|ARTHIST|ASIANAM|ASIAN|ASIALANG|ASTRON|MICROBIO|RP\&SE|BIOCHEM|BIOLOGY|BIOCORE|BME|BOTANY|BMI|CRB|CBE|CHEM|CHICLA|DERM|HDFS|GENBUS|ACCTIS|FINANCE|INFOSYS|INTLBUS|MHR|MARKETNG|OTM|REALEST|CIVENGR|RMI|ACTSCI|CLASSICS|CSCS|COMARTS|CS\&D|COMPLIT|COMPSCI|COUNPSY|CNSRSCI|CURRIC|DYSCI|EASIAN|ECON|EASTDS|ELPA|EDPOL|EDPSYCH|ECE|EMERMED|EMA|EP|EPD|ESL|ENGL|ENTOM|DS|ENVIRST|M\&ENVTOX|FAMMED|FISC|FOLKLORE|FOODSCI|F\&WECOL|FRENCH|GENETICS|GEOG|GLE|GEOSCI|GERMAN|GNS|GREEK|OBS\&GYN|HEBR\-BIB|HEBR\-MOD|HISTORY|MEDHIST|HISTSCI|HORT|HONCOL|ISYE|INTER\-AG|INTEGART|INTEREGR|INTER\-HE|ILS|INTER\-LS|INTEGSCI|INTLST|ITALIAN|JEWISH|JOURN|LANDARC|LCA|LCALANG|LATIN|LACIS|LAW|LEGALST|LIS|LINGUIS|LITTRANS|MATH|ANSCI|ME|MDGENET|MM\&I|MEDPHYS|MEDSC\-M|MEDSC\-V|MEDICINE|MEDIEVAL|MS\&E|ATMOCN|MILSCI|MOLBIOL|MUSIC|MUSPERF|NAVSCI|NEUROL|NEURSURG|NEURODPT|NTP|NE|CNP|NURSING|NUTRSCI|OCCTHER|ONCOLOGY|OPHTHALM|PATH\-BIO|PATH|PEDIAT|PHMSCI|PHMCOL\-M|PHARMACY|PHMPRAC|S\&APHM|PHILOS|DANCE|KINES|PHYTHER|PHYASST|PHYSICS|BMOLCHEM|PHYSIOL|PLPATH|POLISCI|PORTUG|POPHLTH|PSYCHIAT|PSYCH|PUBAFFR|PUBLHLTH|RADIOL|RHABMED|RELIGST|C\&ESOC|SCANDST|STS|SRMED|SLAVIC|SOCWORK|SOC|SOILSCI|SPANISH|STAT|COMPBIO|SURGERY|SURGSCI|THEATRE|URBRPL|GEN\&WS|ZOOLOGY)
    
    commonReqs = ['Freshman standing', 'Sophomore standing', 'Junior standing', 'Senior standing', 'Consent of instructor', 'Graduate/professional standing']
"""


def mapRequisites(courses):
    pass


def __parseRequisite():
    pass
